#!/usr/bin/env bash
# Generate a fresh Open WebUI session signing key.
#
# Output: secret.local.yaml (gitignored). Re-run to rotate; rotating
# invalidates all existing sessions (users will need to log in again).
set -euo pipefail

cd "$(dirname "$0")"

KEY=$(openssl rand -base64 48 | tr -d '=+/' | head -c 64)

cat > secret.local.yaml <<EOF
# Generated by make-secrets.sh. DO NOT EDIT BY HAND. Gitignored.
apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
  namespace: lab-openwebui
type: Opaque
stringData:
  WEBUI_SECRET_KEY: "${KEY}"
EOF

echo "secret.local.yaml written."
echo "(Session-signing key; not user-facing. Rotate by re-running this script.)"
